#! /usr/bin/env python3

import pymongo
from bson import ObjectId

# Data will be stored in the following format on the mongo Database
# database = project selected
# collection = the POI selected (String, struct, etc.)
# data = data related to the POI (type, size, etc.)

# connect to database on a local machine
connection = pymongo.MongoClient('localhost',27017)

# create database
current_database = 'temp' # change string ('temp') here to make a new database for each project***
database = connection[current_database]

# create a collection for each point of interest
point_of_interest = 'placeholder' # change string ('placeholder') here to make a new collection for each point of interest***
collection = database[point_of_interest]
#print("Database connected") #test line to check for proper connection

# begin methods for adding, updating/creating, getting, and removal of data from collections
def insert_data(data): #data needs to be in json format
   document = collection.insert_one(data)
   return document.inserted_id

def update_or_create(document_id,data):
    #avoids duplicates by by creating a new document if the same id does not exist
    document = collection.delete_one({'_id': ObjectId(document_id)},{"$set": data},upsert=True)
    return document.acknowledged

def update_existing(document_id,data):
    document = collection.delete_one({'_id': ObjectId(document_id)}, {"$set": data})
    return document.acknowledged

def remove_data(document_id):
    document = collection.delete_one({'_id': ObjectId(document_id)})
    return document.acknowledged #returns true if deleted

# select a single piece of data to return from a collection(point of interest)
def get_single_data(document_id):
    data = collection.find_one({'_id': ObjectId(document_id)})
    return data

# return everything from a collection(points of interest) in a list format
def get_multiple_data():
    data = collection.find()
    return list(data)

# close the connection to the database
connection.close()

# start of main

# useful notes on database operations:
# data = {"_id": "Project 01","Name", "HP"} #how to define a user defined id *can't use the same id twice!*
# id = insert_data(data) #this will return the id auto generated by mongoDB

# used to change the type of data entered into the database via the if/else statements below
poi_type = "variable" # change "variable" to variable, string, library, function, packet, or struct depding on the type
                      # of data to be entered into the database *note struct not yet implemented*

# edit the following variables with what was found in the static or dynamic analysis
# values that can be stored by the mongo Database are string, integer, boolean, double, Min/Max keys, arrays, timestamp,
# Object, Null, Symbol, Date, ObjectId, Binary data, javascript code and regular expressions
POI_name = "POI_Temp"
POI_value = 3
POI_type = "variable"
POI_size = 2
POI_call_address = ""
POI_destination_address = ""
POI_section = ""
POI_parameter_type_and_order = ""
POI_return_type = ""
POI_return_value = ""
POI_destination_address = ""
POI_python_translation_code = ""
POI_field_name = ""
POI_field_type = ""

# if/else statements to store the corresponding data tot he database
if poi_type == "variable": #variable
    data = {'Variable Name': POI_name}
    insert_data(data)
    data = {'Variable Value': POI_value}
    insert_data(data)
    data = {'Variable Type': POI_type}
    insert_data(data)
    data = {'Variable Size': POI_size}
    insert_data(data)
    data = {'Call From Address': POI_call_address}
    insert_data(data)
elif poi_type == "string": #string
    data = {'String Name': POI_name}
    insert_data(data)
    data = {'String Value': POI_value}
    insert_data(data)
    data = {'String Type': POI_type}
    insert_data(data)
    data = {'String Size': POI_size}
    insert_data(data)
    data = {'Call From Address': POI_call_address}
    insert_data(data)
    data = {'Destination Address': POI_destination_address}
    insert_data(data)
    data = {'Section': POI_section}
    insert_data(data)
elif poi_type == "library": #library
    data = {'Library Name': POI_name}
    insert_data(data)
elif poi_type == "function": #function
    data = {'Function Name': POI_name}
    insert_data(data)
    data = {'Function Value': POI_value}
    insert_data(data)
    data = {'Return Type': POI_return_type}
    insert_data(data)
    data = {'Return value': POI_return_value}
    insert_data(data)
    data = {'Call From Address': POI_call_address}
    insert_data(data)
    data = {'Destination Address': POI_destination_address}
    insert_data(data)
    data = {'Python Translation Code': POI_python_translation_code}
    insert_data(data)
elif poi_type == "packet": #pakect protocol
    data = {'Protocol Name': POI_name}
    insert_data(data)
    data = {'Field Name': POI_field_name}
    insert_data(data)
    data = {'Field Type': POI_field_type}
    insert_data(data)
